### ISSUE TITLE
Failed to run 'override-build': Exit code was 1.

### ISSUE THREAD

**Issue by NavaneethNidadavolu** [ogra1/pi-kiosk-gadget#3]
Building psplash 
+ export TREE=../../../psplash
+ . ../../../psplash/config
+ SPLASH=core_orange_140.png
+ ls /usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
+ FONT=/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
+ echo /usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf+ 
grep -q ^/
+ 
+ echo core_orange_140.png
+ grep -q ^/
+ 
+ SPLASH=../../../psplash/core_orange_140.png
+ git apply ../../../psplash/psplash.patch
error: patch failed: Makefile.am:5
error: Makefile.am: patch does not apply
error: psplash-bar-img.h: No such file or directory
error: patch failed: psplash-config.h:26
error: psplash-config.h: patch does not apply
error: patch failed: psplash.c:21
error: psplash.c: patch does not apply
Failed to run 'override-build': Exit code was 1.

**Comment by ogra1** [comment]
while i will add the missing line to keep this tree buildable, please use
https://github.com/snapcore/pi-gadget
instead... all changes in here have been merged there and the pi-gadget tree is actively maintained by canonical.

**Comment by NavaneethNidadavolu** [comment]
Hey thanks for taking your time and replying back to me. As you have mentioned, I have tried to build using this repo https://github.com/snapcore/pi-gadget and I got another error saying.

Building psplash

    export TREE=./psplash
    . ./psplash/config
    /bin/sh: 29: .: Can't open ./psplash/config
    Failed to run 'override-build': Exit code was 2.

I have tried changing the file permissions using chmod 777 but it didn't work out and i'm stuck again.
Could you please help me out from this situation.

**Comment by ogra1** [comment]
well, i see the file in https://github.com/snapcore/pi-gadget/blob/18-armhf/psplash/config
did you clone the correct branch ?
also, how exactly do you build it and do you use the latest snapcraft snap ?

**Comment by NavaneethNidadavolu** [comment]
Hey, i have the following versions installed on my PC.
`$ snapcraft --version`
snapcraft, version 2.43.1+18.4

`$ snap --version`
snap    2.44.1
snapd   2.44.1
series  16
ubuntu  18.04
kernel  5.3.0-46-generic

These are the steps i followed to make a build:
`$ git clone https://github.com/snapcore/pi-gadget`
`$ cd pi-gadget`
`$ git checkout 18-arm64`
`$ git status`
on branch 18-arm64
nothing to commit, working tree clean

Now i tried this command as shown in the README.md file
`sudo snapcraft clean --destructive-mode`
and i got the following ERROR:
Error: no such option: --destructive-mode

So i tried using it by removing the the flag --destructive-mode. 
`$ sudo snapcraft clean`
and no error showed up.

Next, i tried the following command:
`$ sudo snapcraft snap --target-arch=arm64 --destructive-mode`
Again i got the same Error saying: Error: no such option: --destructive-mode

So i tried using it by removing the the flag --destructive-mode again.
`$ sudo snapcraft snap --target-arch=arm64`
Now it started building the gadget snap and after a while i got this Error:

Building psplash 
+ export TREE=./psplash
+ . ./psplash/config
/bin/sh: 29: .: Can't open ./psplash/config
Failed to run 'override-build': Exit code was 2.

and i can see the file in ./psplash/config
![repo](https://user-images.githubusercontent.com/33155848/78775054-3c89eb80-79b3-11ea-8936-dca2a441c353.png)

I also tried using `$ chmod 777 ./psplash/config` and tried to build again. with the command:
`$ sudo snapcraft snap --target-arch=arm64`
and again got the same Error.

Building psplash 
+ export TREE=./psplash
+ . ./psplash/config
/bin/sh: 29: .: Can't open ./psplash/config
Failed to run 'override-build': Exit code was 2.

**Comment by ogra1** [comment]
> `$ snapcraft --version`
> snapcraft, version 2.43.1+18.4

this is your issue, the apt package is obsolete, replace it with the snap... 
```
sudo apt remove --purge snapcraft
sudo snap install snapcraft --classic
```
you want version 3.11 ...

**Comment by NavaneethNidadavolu** [comment]
Hey, Thanks for your time. the issue is resolved now.
